# Generated by Django 4.2.1 on 2023-06-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nobel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("year", models.PositiveIntegerField()),
                ("country", models.CharField(max_length=50)),
                (
                    "grouping",
                    models.CharField(
                        choices=[
                            ("chemistry", "chemistry"),
                            ("economy", "economy"),
                            ("literature", "literature"),
                            ("nobel peace", "nobel peace"),
                            ("physics", "physics"),
                            ("physiology and medicine", "physiology and medicine"),
                        ],
                        max_length=23,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
