# Generated by Django 4.2.1 on 2023-06-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nobel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("year", models.PositiveIntegerField()),
                ("country", models.CharField(max_length=50)),
                (
                    "grouping",
                    models.CharField(
                        choices=[
                            ("اقتصاد", "اقتصاد"),
                            ("ادبیات", "ادبیات"),
                            ("شیمی", "شیمی"),
                            ("فیزیک", "فیزیک"),
                            ("صلح نوبل", "صلح نوبل"),
                            ("فیزیولوژی و پزشکی", "فیزیولوژی و پزشکی"),
                        ],
                        max_length=23,
                    ),
                ),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
