# Generated by Django 4.2.1 on 2023-06-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nobels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nobel",
            name="user",
        ),
    ]
