# Generated by Django 4.2.1 on 2023-06-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nobels", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="nobel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="nobels.nobel",
            ),
        ),
    ]
