# Generated by Django 4.2.1 on 2023-06-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nobels", "0002_remove_nobel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="nobel",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
    ]
